### PR TITLE
Adding Camera controls to Curve

### PR DESCRIPTION
**Pull request by Danilodum**
camera detection code integration with splineCurve

### CODE REVIEW

**Comment by Danilodum** [comment]
Please take a look, I don't see why it isn't working @SDumasy @jonathanraes @olivier-dikken

**Comment by jonathanraes** [comment]
my camera still doesnt work :-1:

**Comment by Danilodum** [comment]
camera code is commented in app l.52

**Comment by jonathanraes** [comment]
merge required to get the updated code to customCurveMesh, splinecureve is being refactored in another branch and will be merged into customCurveMesh when it is done.

**Pull request merged**
