### PR TITLE
As a user I want to be able to use my body to manipulate the wave

### PR DESCRIPTION
**Pull request by Danilodum**

### CODE REVIEW

**Comment by Danilodum** [comment]
Please review @SDumasy @sndumasy @jonathanraes @olivier-dikken

**Comment by Danilodum** [comment]
coverage > 75%, 3 findbugs errors on exposing mutable objects. Our current implementation requires it, we are looking for a fix, other tools have no complaints, stable code

**Comment by olivier-dikken** [comment]
works. seems ready to merge

**Comment by jonathanraes** [comment]
Bug in the curve since the removing of the parentheses

**Pull request merged**
