### PR TITLE
Obstacle

### PR DESCRIPTION
**Pull request by ghost**
Renamed packages, added Obstacles

### CODE REVIEW

**Comment by jonathanraes** [comment]
Theres no travis.yml yet.
Also, movingBoxTest seems to run forever?

**Comment by Danilodum** [comment]
build failing, junit not available, might be caused by package rename, but pom is also probably outdated

**Comment by jonathanraes** [comment]
yeah JUnit is failing because of pom.xml. MovingBoxTest still doesnt end though

**Comment by Danilodum** [comment]
``` java
changeMoveUpTest()
moveDownTest()
```

in 

``` java
Class MovingBoxTest
```

are infinite loops. 

 @SDumasy

**Comment by Danilodum** [comment]
checkstyle, pmd and findbugs errors in

``` java
Class Obstacle
Class ObstacleFactory
Class MovingBox
Class SplineCurve
```

as well as in outdated

``` java
Class App
Class PhysicsController
```

 @SDumasy

**Comment by jonathanraes** [comment]
fixed some last warnings and made draw() abstract, think its ready for merge now

**Comment by Danilodum** [comment]
not merge ready.

findbugs: 6 bugs
PMD: 3 relevant violations
checkstyle: 94 warnings

**Comment by Danilodum** [comment]
please review @SDumasy @jonathanraes

**Comment by jonathanraes** [comment]
I think it can be merged, although the balls still act buggy moving through the obstacle sometimes

**Comment by jonathanraes** [comment]
I was wrong, the speed of the obstacle was dependent on the framerate. Now fixed

**Comment by Danilodum** [comment]
Looks good, no tool errors, merging

**Pull request merged**
