### PR TITLE
Release

### PR DESCRIPTION
**Pull request by jonathanraes**

### CODE REVIEW

**Comment by jonathanraes** [comment]
Pretty big enhancement

**Comment by jonathanraes** [comment]
Working build and decent test coverage. Whale warning block is still pretty big .

**Comment by jonathanraes** [comment]
also, inputstate can be cleaned up for release

**Comment by Danilodum** [comment]
Whale is also quite slow

**Comment by Danilodum** [comment]
Penguin rotation is also quite weird still

**Comment by jonathanraes** [comment]
fixed penguinrotation in PenguinRotation branch

**Pull request merged**
